### PR TITLE
add Chinese (Traditional) translation

### PR DESCRIPTION
**Pull request by cges30901**
Chinese (Traditional) translation for LTE Cleaner.
(I wanted to test the translation but LTE Cleaner crashed as soon as I launch it)

### CODE REVIEW

**Comment by TheRedSpy15** [comment]
Thank you so much for this!

I will definitely be looking into the crash, hopefully will be fixed within the week

**Comment by TheRedSpy15** [comment]
I just published an update which hopefully fixes the crash

Please try it and let me know if it is still crashing on startup

**Comment by cges30901** [comment]
Thank you! it does not crash now.

**Comment by cges30901** [comment]
Sorry, it seems that the crash is because I didn't build LTE Cleaner correctly.

**Pull request merged**
